// medicine_8.js
module.exports = {
	title: 'Medicine Words',
	full: 'medicine',
	language: 'english',
	type: 'D',
	topic: 'MD',
	url: 'https://en.wikipedia.org/wiki/List_of_pharmaceutical_companies',
	element: '#mw-content-text ul li a',
	filter: [
	 '1 Alphabetical listing',
     '1.1 1-A',
     '1.2 B-D',
     '1.3 E-L',
     '1.4 M',
     '1.5 N',
     '1.6 O',
     '1.7 P',
     '1.8 R',
     '1.9 S-T',
     '1.10 U-Z',
     '2 See also',
     '3 References',
     '3M Pharmaceutica',
     'List of biotechnology companies',
     'List of pharmaceutical manufacturers in the UK',
     'more...',
     'in Bangladesh',
     'in India',
     'in China',
     'in Pakistan',
     'in the UK',
     'Anatomy of an Epidemic',
     'Mad in America',
     'List of drugs',
     'List of largest pharmaceutical settlements',
     'List of off-label promotion pharmaceutical settlements',
     'List of pharmaceutical manufacturers in the UK',
     'Pharmaceutical industry by country',
     'in the UK',
     'of the US',
     'Pharmaceutical companies of the United States',
     'of Australia',
     'of Canada',
     'of Finland',
     'of India',
     'of Japan',
     'of Switzerland',
     'of the UK',
     'v',
     't',
     'e',
     'Fitness wear',
     'Swimwear',	
     'Champagne houses',
     'Chocolate',
     'Coffee',
     'Food',
     'Soft drinks',
     'Tea',
     'Coffeehouses',
     'Ice cream parlors',
     'Restaurant chains',
     'Casual dining',
     'Fast food',
     'Pizza',
     'Revolving',
     'Aerial lift',
     'Aircraft',
     'Automobile',
     'Astronomical instruments',
     'Bicycles',
     'CIGS',
     'Computer hardware',
     'Computer systems',
     'Cymbals',
     'Dump trucks',
     'Electric vehicle batteries',
     'Electronics',
     'Flash memory controller',
     'Games',
     'Horns',
     'Locomotive',
     'Microphone',
     'Modern armament',
     'Motorcycles',
     'Rolling stock',
     'Steel',
     'Stuffed toys',
     'Touch-solution',
     'Traction motors',
     'Radio-controlled model aircraft kits',
     'Scooters',
     'Semiconductors',
     'Equipment',
     'Solid-state drives',
     'Tractors',	
     'Wind turbines',
     'Animation',
     'Anime',
     'Cable television',
     'Children\'s books',
     'Records',
     'Television networks',
     'Video games',
     'Developers',
     'Fighting games',
     'Indie',
     'Publishers',
     'Book clubs',
     'Bookstores',
     'Chains',
     'Independent',
     'Convenience',
     'Cooperatives',
     'Department',
     'Hypermarkets',
     'Supermarkets',
     'Superstores',
     'Advertising technology',
     'Automation integrator',
     'Biotechnology',
     'Computer-aided design',
     'Electronic design automation',
     'Enterprise search',
     'Oilfield service',
     'Oil exploration and production',
     'Photovoltaics',
     'Public utilities',
     'Silicon',
     'Solar thermal power',
     'Telephone',
     'Banking',
     'Casinos',
     'Construction equipment rental',
     'Hotels',
     'Law firms',
     'Management consulting',
     'Marketing research',
     'Mobile network',
     'Airlines',
     'Charter',
     'Defunct',
     'Holding',
     'Low-cost',
     'Passenger',
     'Regional',
     'Bus',
     'Cruise lines',
     'Ferry',
     'Railway',
     'Ship',
     'Automobile',
     'Freight',
     'Passenger'	
	],
	clean: function(text) {

		text = text.replace(' (company)', '');
		text = text.replace('\'', '');

		var output = {
			type: "string",
			data: text
		};

		return output;
	}
};